version: "3"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      # Replace with your actual database credentials
      DATABASE_HOST: "db"
      DATABASE_PORT: "3306"
      DATABASE_USER: "stud"
      DATABASE_PASSWORD: "stud"
      DATABASE_NAME: "archdb"
    volumes:
      - .:/app

  db:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: "stud"
      MYSQL_DATABASE: "archdb"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
